[workspace]
channels = ["conda-forge"]
name = "autoformer"
platforms = ["osx-arm64", "osx-64", "win-64", "linux-64"]

[tasks]
install = "pip install neuralforecast darts tabulate pyarrow"
main = { cmd = "python main.py", depends-on = ["install"] }

[dependencies]

python = "3.13.*"
pip = "*"
numpy = "*"
pandas = "*"
tqdm = "*"
packaging = "*"