# Models Registry Configuration
# This file serves as a central registry of all available forecasting models
# for both forecast_stats.py and forecast_neural.py scripts

# Statistical Models (forecast_stats.py)

[historic_average]
script = "forecast_stats.py"
display_name = "Historic Average"
table_name = "HistAvg"
description = "Simple average of historical values"

# [seasonal_naive]
# script = "forecast_stats.py"
# display_name = "Seasonal Naive"
# table_name = "SeasNaive"
# description = "Last seasonal observation as forecast"

[auto_arima]
script = "forecast_stats.py"
display_name = "Auto ARIMA"
table_name = "ARIMA"
description = "Automatic ARIMA model selection"

# [auto_ces]
# script = "forecast_stats.py"
# display_name = "Auto CES"
# table_name = "CES"
# description = "Automatic Complex Exponential Smoothing"

# [auto_ets]
# script = "forecast_stats.py"
# display_name = "Auto ETS"
# table_name = "ETS"
# description = "Automatic Error-Trend-Seasonality model"

# [croston]
# script = "forecast_stats.py"
# display_name = "Croston"
# table_name = "Croston"
# description = "Croston method for intermittent demand"

# [dot]
# script = "forecast_stats.py"
# display_name = "Dynamic Optimized Theta"
# table_name = "DOT"
# description = "Dynamic optimized Theta method"

# [holt_winters]
# script = "forecast_stats.py"
# display_name = "Holt-Winters"
# table_name = "HoltWint"
# description = "Holt-Winters exponential smoothing"

[ses]
script = "forecast_stats.py"
display_name = "Simple Exponential Smoothing"
table_name = "SES"
description = "Simple exponential smoothing with alpha=0.1"

[theta]
script = "forecast_stats.py"
display_name = "Theta"
table_name = "Theta"
description = "Theta method for forecasting"

# Neural Models (forecast_neural.py)
# All neural models use automatic hyperparameter optimization with Optuna

[auto_deepar]
script = "forecast_neural.py"
display_name = "Auto DeepAR"
table_name = "DeepAR"
description = "Auto hyperparameter optimization for DeepAR with LSTM encoder-decoder"

[auto_nbeats]
script = "forecast_neural.py"
display_name = "Auto N-BEATS"
table_name = "NBEATS"
description = "Auto hyperparameter optimization for N-BEATS neural network"

[auto_nhits]
script = "forecast_neural.py"
display_name = "Auto N-HiTS"
table_name = "NHITS"
description = "Auto hyperparameter optimization for N-HiTS hierarchical interpolation"

[auto_dlinear]
script = "forecast_neural.py"
display_name = "Auto DLinear"
table_name = "DLinear"
description = "Auto hyperparameter optimization for DLinear decomposition model"

[auto_nlinear]
script = "forecast_neural.py"
display_name = "Auto NLinear"
table_name = "NLinear"
description = "Auto hyperparameter optimization for NLinear normalization model"

[auto_vanilla_transformer]
script = "forecast_neural.py"
display_name = "Auto Vanilla Transformer"
table_name = "Transformer"
description = "Auto hyperparameter optimization for Vanilla Transformer"

[auto_tide]
script = "forecast_neural.py"
display_name = "Auto TiDE"
table_name = "TiDE"
description = "Auto hyperparameter optimization for TiDE (Time-series Dense Encoder)"

[auto_kan]
script = "forecast_neural.py"
display_name = "Auto KAN"
table_name = "KAN"
description = "Auto hyperparameter optimization for Kolmogorov-Arnold Networks"

# Note: auto_lstm temporarily disabled due to tensor dimension mismatch issues
# [auto_lstm]
# script = "forecast_neural.py"
# display_name = "Auto LSTM"
# table_name = "LSTM"
# description = "Auto hyperparameter optimization for LSTM encoder-decoder"