[workspace]
channels = ["conda-forge"]
name = "tide"
platforms = ["win-64", "linux-64"]

[tasks]
install = "pip install darts tabulate"
main = { cmd = "python main.py", depends-on = ["install"]}

[system-requirements]
cuda = "12.8"

[dependencies]

python = "3.13.*"
pip = "*"
numpy = "*"
pandas = "*"
tqdm = "*"
packaging = "*"
scipy = "*"
statsmodels = "*"
pyarrow = "*"
fastparquet = "*"
darts = "*"
tabulate = "*"

[pypi-dependencies]
torch = { version = ">=2.5.1", index = "https://download.pytorch.org/whl/cu128" }
torchvision = { version = ">=0.20.1", index = "https://download.pytorch.org/whl/cu128" }
lightning = { version = "==2.5.*" }