# Frequency Key:
# https://stackoverflow.com/questions/35339139/what-values-are-valid-in-pandas-freq-tags
# Alias    Description
# -----    ---------
# B       business day frequency
# C       custom business day frequency
# D       calendar day frequency
# W       weekly frequency
# ME      month end frequency
# SME     semi-month end frequency (15th and end of month)
# BME     business month end frequency
# CBME    custom business month end frequency
# MS      month start frequency
# SMS     semi-month start frequency (1st and 15th)
# BMS     business month start frequency
# CBMS    custom business month start frequency
# QE      quarter end frequency
# BQE     business quarter end frequency
# QS      quarter start frequency
# BQS     business quarter start frequency
# YE      year end frequency
# BYE     business year end frequency
# YS      year start frequency
# BYS     business year start frequency
# h       hourly frequency
# bh      business hour frequency
# cbh     custom business hour frequency
# min     minutely frequency
# s       secondly frequency
# ms      milliseconds
# us      microseconds
# ns      nanoseconds

################################################################################
[cds_bond_basis]
data_module_name = "CDS Bond Basis"
data_module_description = """
Contains code that replicated the CDS bond basis calculations from Segmented Arbitrage
"""
required_data_sources = ["open_source_bond", "wrds_markit"]

################################################################################
[cds_returns]
required_data_sources = ["fed_yield_curve", "wrds_markit"]

################################################################################
[cip]
data_module_name = "CIP"
data_module_description = """
Contains code that replicated the CIP arbitrage calculations from Segmented Arbitrage
"""
required_data_sources = ["bloomberg_terminal"]

################################################################################
[commodities]
required_data_sources = ["bloomberg_terminal", "wrds_datastream"]

################################################################################
[corp_bond_returns]
required_data_sources = ["open_source_bond"]

[corp_bond_returns.ftsfr_corp_bond_returns]
description = """This data module contains the returns of individual corporate bonds sourced from the TRACE database."""
frequency = "ME"
seasonality = 12

[corp_bond_returns.ftsfr_corp_bond_portfolio_returns]
description = """This data module contains the returns of the corporate bond portfolios formed as per the methodology of Nozawa (2017)."""
frequency = "ME"
seasonality = 12

################################################################################
[us_treasury_returns]
required_data_sources = ["wrds_crsp"]

[us_treasury_returns.ftsfr_treas_bond_returns]
description = """This data module contains the returns of individual treasury bonds sourced from the CRSP database."""
frequency = "ME"
seasonality = 12

[us_treasury_returns.ftsfr_treas_bond_portfolio_returns]
description = """This data module contains the returns of the treasury bond portfolios formed as per the methodology of Gurkaynak, Sack, and Wright (2011)."""
frequency = "ME"
seasonality = 12

################################################################################

[crb_commodity]
required_data_sources = ["bloomberg_terminal"]


################################################################################
[fed_yield_curve]
data_module_name = "Fed Yield Curve"
data_module_description = """
This data module contains the Fed Yield Curve estimation results from Gurkaynak, 
Sack, and Wright (2011). The data will take the form, for example, of a panel of 
zero-coupon yields for various points on the yield curve. 
"""
required_data_sources = ["fed_yield_curve"]

[fed_yield_curve.ftsfr_treas_yield_curve_zero_coupon]
description = """Nelson-Seigel-Svensson zero-coupon yield curve, 
tenors 1-30 years, 1961-present"""
frequency = "D"
seasonality = 365 # Calendar days per year (or 252 for business days)

################################################################################
[foreign_exchange]
required_data_sources = ["bloomberg_terminal"]

################################################################################
[futures_returns]
required_data_sources = ["bloomberg_terminal", "wrds_datastream"]

################################################################################
[he_kelly_manela]
required_data_sources = ["he_kelly_manela"]

[he_kelly_manela.ftsfr_he_kelly_manela_factors_monthly]
description = """Monthly factors from He, Kelly, and Manela (2017)"""
frequency = "ME"
seasonality = 12

[he_kelly_manela.ftsfr_he_kelly_manela_factors_daily]
description = """Daily factors from He, Kelly, and Manela (2017)"""
frequency = "D"
seasonality = 252

[he_kelly_manela.ftsfr_he_kelly_manela_all]
description = """All factors from He, Kelly, and Manela (2017)"""
frequency = "D"
seasonality = 252


################################################################################
[ken_french_data_library]
required_data_sources = ["ken_french_data_library"]

[ken_french_data_library.ftsfr_french_portfolios_25_daily_size_and_bm]
description = """Daily Fama-French 25 portfolios based on size and book-to-market"""
frequency = "D"
seasonality = 252

[ken_french_data_library.ftsfr_french_portfolios_25_daily_size_and_op]
description = """Daily Fama-French 25 portfolios based on size and operating profitability"""
frequency = "D"
seasonality = 252

[ken_french_data_library.ftsfr_french_portfolios_25_daily_size_and_inv]
description = """Daily Fama-French 25 portfolios based on size and investment"""
frequency = "D"
seasonality = 252


################################################################################
[nyu_call_report]
required_data_sources = ["nyu_call_report"]

[nyu_call_report.ftsfr_nyu_call_report_leverage]
description = """From call report data, leverage for each rssdid, 1976-2020"""
frequency = "QE"
seasonality = 4  # Quarters per year

[nyu_call_report.ftsfr_nyu_call_report_holding_company_leverage]
description = """From call report data, leverage for each bhcid, 1976-2020"""
frequency = "QE"
seasonality = 4

[nyu_call_report.ftsfr_nyu_call_report_cash_liquidity]
description = """From call report data, cash liquidity for each rssdid, 1976-2020"""
frequency = "QE"
seasonality = 4

[nyu_call_report.ftsfr_nyu_call_report_holding_company_cash_liquidity]
description = """From call report data, cash liquidity for each bhcid, 1976-2020"""
frequency = "QE"
seasonality = 4

################################################################################
[options]
required_data_sources = ["wrds_optionmetrics"]

[options.ftsfr_hkm_option_returns]
description = """From optionmetrics data, option returns, 1996-Present"""
frequency = "D"
seasonality = 252 # Business days per year

[options.ftsfr_cjs_option_returns]
description = """From optionmetrics data, option returns, 1996-Present"""
frequency = "D"
seasonality = 252 # Business days per year

################################################################################
[sovereign_bonds]
required_data_sources = ["wrds_crsp"]

################################################################################
[wrds_bank_premium]
required_data_sources = ["wrds_bank_premium"]

################################################################################
[wrds_crsp_compustat]
required_data_sources = ["wrds_compustat", "wrds_crsp", "wrds_crsp_compustat"]

[wrds_crsp_compustat.ftsfr_CRSP_monthly_stock_ret]
description = """CRSP monthly stock returns, 1926-present"""
frequency = "ME"
seasonality = 12  # Months per year

[wrds_crsp_compustat.ftsfr_CRSP_monthly_stock_retx]
description = """CRSP monthly stock returns (without dividends), 1926-present"""
frequency = "ME"
seasonality = 12