[workspace]
channels = ["conda-forge"]
name = "ftsfr"
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[tasks]
main = "python -m doit"

[dependencies]
python = "3.12.*"


[pypi-dependencies]
# Development Dependencies (merged from feature)
arch = "==7.1.0"
black = "==24.10.0"
doit = "*"
ipywidgets = "==8.1.5"
matplotlib = "*" 
numpy = "*"
openpyxl = "==3.1.3"
packaging = "<23.3" # Pinned to satisfy wrds requirement
pandas = "==2.2.3"
polars = "*" # Polars is available on both, using PyPI here
pre-commit = "==4.0.1"
psycopg2-binary = "==2.9.10"
pyarrow = "*"
pydata-sphinx-theme = "==0.16.1"
pytest = "==8.3.4"
python-decouple = "*"
scikit-learn = "*"
scipy = "~=1.12.0" 
seaborn = "==0.13.2"
statsmodels = "==0.14.3"
thefuzz = "*"
toml = "*"
torch = "==2.6.0" # Moved from conda dependencies
wrds = "==3.2.0"
yfinance = "==0.2.43"