[workspace]
channels = ["conda-forge"]
name = "deepar"
platforms = ["osx-arm64", "osx-64", "win-64", "linux-64"]

[tasks]
install = "pip install gluonts[torch] lightning"
main = { cmd = "python main.py", depends-on = ["install"] }

[dependencies]

python = "3.13.*"
pip = "*"
numpy = "*"
pandas = "*"
tqdm = "*"
packaging = "*"
scipy = "*"
statsmodels = "*"
pyarrow = "*"
fastparquet = "*"
gluonts = "*"
tabulate = "*"