[workspace]
channels = ["conda-forge"]
name = "timesfm"
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[tasks]
post-install = "pip install timesfm[torch] darts"
main = { cmd= "python main.py", depends-on = ["post-install"]}

[dependencies]
python = "3.11"
pip = "*"
python-decouple = "*"
toml = "*"
pandas = "*"
numpy = "*"
statsmodels = "*"
tqdm = "*"
pyarrow = "*"
gfortran = "*"