[workspace]
channels = ["conda-forge"]
name = "ffnn"
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[tasks]
post-install = "pip install 'gluonts[torch]' lightning"
main = { cmd= "python main.py", depends-on = ["post-install"]}

[dependencies]
python = "3.12.*"
pip = "*"
python-decouple = "*"
toml = "*"
pandas = "*"
numpy = "*"
pyarrow = "*"
gfortran = "*"
gluonts = "*"
pytorch = "*"