[workspace]
channels = ["conda-forge"]
name = "models_darts"
platforms = ["osx-arm64", "osx-64", "win-64", "linux-64"]

[tasks]
install = "pip install darts tabulate catboost"
run = { cmd = "python run_model.py", depends-on = ["install"] }
run-controller = { cmd = "python model_controller.py", depends-on = ["install"] }

[feature.g]
system-requirements = {cuda = "12.8"}
platforms = ["win-64", "linux-64"]

[feature.g.pypi-dependencies]
torch = { version = ">=2.5.1", index = "https://download.pytorch.org/whl/cu128" }
torchvision = { version = ">=0.20.1", index = "https://download.pytorch.org/whl/cu128" }
lightning = { version = "==2.5.*" }

[feature.c.pypi-dependencies]
torch = { version = ">=2.5.1", index = "https://download.pytorch.org/whl/cpu" }
torchvision = { version = ">=0.20.1", index = "https://download.pytorch.org/whl/cpu" }
lightning = { version = "==2.5.*" }

[dependencies]
python = "3.13.*"
pip = "*"
numpy = "*"
pandas = "*"
tqdm = "*"
packaging = "*"
scipy = "*"
statsmodels = "*"
pyarrow = "*"
fastparquet = "*"
darts = "*"
tabulate = "*"
scikit-learn = "*"  # For pooled regression
prophet = "*"  # For Prophet model

[environments]
gpu = { features = ["g"] }
default = { features = ["c"] }