[workspace]
channels = ["conda-forge"]
name = "models_timesfm"
platforms = ["osx-arm64", "osx-64", "win-64", "linux-64"]

[tasks]
install = "pip install darts tabulate timesfm"
run = { cmd = "python run_model.py --model timesfm", depends-on = ["install"] }

[dependencies]
python = "3.11.*"  # TimesFM requires 3.11
pip = "*"
numpy = "*"
pandas = "*"
tqdm = "*"
packaging = "*"
scipy = "*"
statsmodels = "*"
pyarrow = "*"
fastparquet = "*"
darts = "*"
tabulate = "*"