[workspace]
channels = ["conda-forge"]
name = "ftsfr_models"
platforms = ["osx-arm64", "osx-64", "win-64", "linux-64"]

[tasks]
install = "pip install darts gluonts neuralforecast timesfm catboost tabulate tomli"
run = { cmd = "python run_model.py", depends-on = ["install"] }
run-controller = { cmd = "python model_controller.py", depends-on = ["install"] }
test-gpu = "python test_gpu.py"

[feature.gpu]
system-requirements = {cuda = "12.8"}
platforms = ["win-64", "linux-64"]

[feature.gpu.pypi-dependencies]
torch = { version = ">=2.5.1", index = "https://download.pytorch.org/whl/cu128" }
torchvision = { version = ">=0.20.1", index = "https://download.pytorch.org/whl/cu128" }
lightning = { version = "==2.5.*" }

[feature.cpu.pypi-dependencies]
torch = { version = ">=2.5.1", index = "https://download.pytorch.org/whl/cpu" }
torchvision = { version = ">=0.20.1", index = "https://download.pytorch.org/whl/cpu" }
lightning = { version = "==2.5.*" }

[dependencies]
python = "3.11.*"  # TimesFM requires 3.11
pip = "*"
numpy = "*"
pandas = "*"
tqdm = "*"
packaging = "*"
scipy = "*"
statsmodels = "*"
pyarrow = "*"
fastparquet = "*"
tabulate = "*"
scikit-learn = "*"
prophet = "*"
tomli = "*"  # For TOML reading in Python < 3.11

[environments]
gpu = { features = ["gpu"] }
default = { features = ["cpu"] }