[workspace]
channels = ["conda-forge"]
name = "models_gluonts"
platforms = ["linux-64"]  # GluonTS typically works best on Linux

[tasks]
install = "pip install gluonts darts tabulate"
run = { cmd = "python run_model.py", depends-on = ["install"] }
run-controller = { cmd = "python model_controller.py", depends-on = ["install"] }

[system-requirements]
cuda = "12.8"

[dependencies]
python = "3.13.*"
pip = "*"
numpy = "*"
pandas = "*"
tqdm = "*"
packaging = "*"
scipy = "*"
statsmodels = "*"
pyarrow = "*"
fastparquet = "*"
gluonts = "*"
tabulate = "*"

[pypi-dependencies]
torch = { version = ">=2.5.1", index = "https://download.pytorch.org/whl/cu128" }
torchvision = { version = ">=0.20.1", index = "https://download.pytorch.org/whl/cu128" }
lightning = { version = "==2.5.*" }