# Simplified Models Configuration for forecast.py
# This file defines all available forecasting models for the CLI script

[naive]
library = "statsforecast"
class = "Naive"
display_name = "Naive"
table_name = "Naive"

[seasonal_naive]
library = "statsforecast"
class = "SeasonalNaive"
display_name = "Seasonal Naive"
table_name = "SN"

# [seasonal_es_optimized]
# library = "statsforecast"
# class = "SeasonalExponentialSmoothingOptimized"
# display_name = "Seasonal ES Optimized"


[auto_theta]
library = "statsforecast"
class = "AutoTheta"
display_name = "AutoTheta"
table_name = "Theta"
[auto_theta.params]
decomposition_type = "additive"

#TBATS not in nixtlaverse


[auto_ets]
library = "statsforecast"
class = "AutoETS"
display_name = "AutoETS"
table_name = "ETS"
[auto_ets.params]
model = "ZZZ"

# DHR-ARIMA not in nixtlaverse
# (Dynamic Harmonic Regression - ARIMA)

# StatsForecast Models
# [auto_arima]
# library = "statsforecast"
# class = "AutoARIMA"
# display_name = "AutoARIMA"
# # season_length will be set dynamically from dataset config


[auto_arima_fast]
library = "statsforecast"
class = "AutoARIMA"
display_name = "AutoARIMA"
table_name = "ARIMA"
[auto_arima_fast.params]
approximation = true
stepwise = true
max_p = 2
max_q = 2
max_P = 1
max_Q = 1
nmodels = 10


[deepar]
library = "neuralforecast"
class = "DeepAR"
display_name = "DeepAR"
table_name = "DeepAR"
[deepar.params]
h = 1
loss = "DistributionLoss"
input_size = 12
lstm_hidden_size = 32
max_steps = 100

## This model is having difficulty
# [auto_deepar]
# library = "neuralforecast"
# class = "AutoDeepAR"
# display_name = "AutoDeepAR"
# [auto_deepar.params]
# h = 1
# loss = "DistributionLoss"
# [auto_deepar.params.config]
# max_steps = 50
# input_size = 12
# lstm_hidden_size = 32


[nbeats]
library = "neuralforecast"
class = "NBEATS"
display_name = "NBEATS"
table_name = "NBEATS"
[nbeats.params]
h = 1
loss = "MAE"
input_size = 12
max_steps = 100
mlp_units = [[32, 32], [32, 32], [32, 32]]
stack_types = ["identity", "identity"]

## This model is having difficulty
# [auto_nbeats]
# library = "neuralforecast"
# class = "AutoNBEATS"
# display_name = "AutoNBEATS"
# [auto_nbeats.params]
# h = 1
# loss = "MAE"
# [auto_nbeats.params.config]
# max_steps = 50
# val_check_steps = 10
# input_size = 12
# mlp_units = [[32, 32], [32, 32], [32, 32]]


[nhits]
library = "neuralforecast"
class = "NHITS"
display_name = "NHITS"
table_name = "NHITS"
[nhits.params]
h = 1
loss = "MAE"
input_size = 12
max_steps = 100
mlp_units = [[16, 16], [16, 16], [16, 16]]

## This model is having difficulty
# [auto_nhits]
# library = "neuralforecast"
# class = "AutoNHITS"
# display_name = "AutoNHITS"
# [auto_nhits.params]
# h = 1
# loss = "MAE"
# [auto_nhits.params.config]
# max_steps = 50
# val_check_steps = 10
# input_size = 12
# mlp_units = [[16, 16], [16, 16], [16, 16]]


[dlinear]
library = "neuralforecast"
class = "DLinear"
display_name = "DLinear"
table_name = "DLinear"
[dlinear.params]
h = 1
loss = "MAE"
input_size = 12
max_steps = 100

## This model is having difficulty
# [auto_dlinear]
# library = "neuralforecast"
# class = "AutoDLinear"
# display_name = "AutoDLinear"
# [auto_dlinear.params]
# h = 1
# loss = "MAE"
# [auto_dlinear.params.config]
# max_steps = 50
# val_check_steps = 10
# input_size = 12


[nlinear]
library = "neuralforecast"
class = "NLinear"
display_name = "NLinear"
table_name = "NLinear"
[nlinear.params]
h = 1
loss = "MAE"
input_size = 12
max_steps = 100

## This model is having difficulty
# [auto_nlinear]
# library = "neuralforecast"
# class = "AutoNLinear"
# display_name = "AutoNLinear"
# [auto_nlinear.params]
# h = 1
# loss = "MAE"
# [auto_nlinear.params.config]
# max_steps = 50
# val_check_steps = 10
# input_size = 12


[vanilla_transformer]
library = "neuralforecast"
class = "VanillaTransformer"
display_name = "VanillaTransformer"
table_name = "Transformer"
[vanilla_transformer.params]
h = 1
loss = "MAE"
input_size = 12
max_steps = 100
hidden_size = 32

## This model is having difficulty
# [auto_vanilla_transformer]
# library = "neuralforecast"
# class = "AutoVanillaTransformer"
# display_name = "AutoVanillaTransformer"
# [auto_vanilla_transformer.params]
# h = 1
# loss = "MAE"
# [auto_vanilla_transformer.params.config]
# max_steps = 50
# val_check_steps = 10
# input_size = 12
# hidden_size = 32


[tide]
library = "neuralforecast"
class = "TiDE"
display_name = "TiDE"
table_name = "TiDE"
[tide.params]
h = 1
loss = "MAE"
input_size = 12
hidden_size = 512
decoder_output_dim = 32
temporal_decoder_dim = 128
dropout = 0.3
max_steps = 100


[kan]
library = "neuralforecast"
class = "KAN"
display_name = "KAN"
table_name = "KAN"
[kan.params]
h = 1
loss = "MAE"
input_size = 12
grid_size = 5
spline_order = 3
n_hidden_layers = 1
hidden_size = 512
max_steps = 100


# Very slow
# [timesnet]
# library = "neuralforecast"
# class = "TimesNet"
# display_name = "TimesNet"
# [timesnet.params]
# h = 1
# loss = "MAE"
# input_size = 12
# hidden_size = 64
# dropout = 0.1
# conv_hidden_size = 64
# top_k = 5
# num_kernels = 6
# max_steps = 100